<?php

declare(strict_types=1);

namespace Tests\Feature\Installer;

use App\Services\Install\EnvFile;
use Dotenv\Dotenv;
use InvalidArgumentException;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;

/**
 * The one file the installer writes, and the one it cannot afford to get wrong.
 *
 * Database and SMTP passwords are generated by hosting control panels, which means they are
 * full of exactly the characters dotenv treats as syntax: `#` starts a comment, `$` starts an
 * interpolation, a space ends an unquoted value. A password mangled here produces an
 * installation that finishes cleanly and then cannot connect to anything — so every awkward
 * value is written and then parsed back through phpdotenv itself, not through this class's
 * own reader.
 */
final class EnvFileTest extends InstallerTestCase
{
    /**
     * @return array<string, array{string}>
     */
    public static function awkwardValues(): array
    {
        return [
            'plain' => ['planvio'],
            'spaces' => ['Acme Projects Ltd'],
            'hash' => ['p#ssw0rd'],
            'dollar' => ['a$b$c'],
            'braced variable' => ['${APP_NAME}'],
            'double quote' => ['say "hello"'],
            'single quote' => ["it's fine"],
            'both quotes' => ['he said "it\'s fine"'],
            'backslash' => ['domain\\user'],
            'equals' => ['key=value'],
            'inline comment lookalike' => ['value # not a comment'],
            'leading space' => ['  padded'],
            'punctuation soup' => ['!@%^&*()_+-=[]{};:,.<>/?|~`'],
            'unicode' => ['naïve café 東京'],
            'generated password' => ['x7#Kq$2z!Lm@9Pw&'],
        ];
    }

    #[Test]
    #[DataProvider('awkwardValues')]
    public function a_value_survives_a_round_trip_through_dotenv(string $value): void
    {
        $rendered = EnvFile::fromString("APP_NAME=Planvio\n")
            ->set('DB_PASSWORD', $value)
            ->render();

        $path = $this->sandbox.DIRECTORY_SEPARATOR.'.env.roundtrip';
        file_put_contents($path, $rendered);

        // Parsed by phpdotenv, which is what Laravel will use to read this file for real.
        $parsed = Dotenv::parse($rendered);

        $this->assertSame($value, $parsed['DB_PASSWORD'], "Mangled: {$rendered}");
        $this->assertSame($value, EnvFile::fromFile($path)->get('DB_PASSWORD'));
    }

    #[Test]
    public function it_replaces_a_value_without_disturbing_anything_around_it(): void
    {
        $original = <<<'ENV'
            # --- Database ---------------------------------------------------------------
            # On cPanel the database name is prefixed with your account name.
            DB_CONNECTION=mysql
            DB_HOST=127.0.0.1
            DB_DATABASE=

            # --- Mail -------------------------------------------------------------------
            MAIL_MAILER=log
            ENV;

        $rendered = EnvFile::fromString($original)
            ->set('DB_DATABASE', 'acme_planvio')
            ->set('DB_HOST', 'localhost')
            ->render();

        $this->assertStringContainsString('# --- Database ', $rendered);
        $this->assertStringContainsString('# On cPanel the database name is prefixed', $rendered);
        $this->assertStringContainsString('# --- Mail ', $rendered);
        $this->assertStringContainsString('DB_DATABASE=acme_planvio', $rendered);
        $this->assertStringContainsString('DB_HOST=localhost', $rendered);
        $this->assertSame(1, substr_count($rendered, 'DB_HOST='), 'A replaced key must not be duplicated.');
    }

    #[Test]
    public function an_unknown_key_is_appended_rather_than_lost(): void
    {
        $rendered = EnvFile::fromString("APP_NAME=Planvio\n")->set('AI_ENABLED', 'true')->render();

        $this->assertSame('true', Dotenv::parse($rendered)['AI_ENABLED']);
    }

    #[Test]
    public function a_commented_out_key_is_not_mistaken_for_an_assignment(): void
    {
        $rendered = EnvFile::fromString("# DB_PASSWORD=leave-me\nDB_PASSWORD=real\n")
            ->set('DB_PASSWORD', 'new')
            ->render();

        $this->assertStringContainsString('# DB_PASSWORD=leave-me', $rendered);
        $this->assertSame('new', Dotenv::parse($rendered)['DB_PASSWORD']);
    }

    #[Test]
    public function an_empty_value_is_written_as_an_empty_assignment(): void
    {
        $rendered = EnvFile::fromString('')->set('MAIL_USERNAME', '')->render();

        $this->assertSame("MAIL_USERNAME=\n", $rendered);
        $this->assertSame('', Dotenv::parse($rendered)['MAIL_USERNAME']);
    }

    #[Test]
    public function a_value_the_format_cannot_represent_is_refused_rather_than_truncated(): void
    {
        // Silently cutting a password at the newline would produce an installation whose
        // administrator cannot sign in and cannot see why.
        $this->expectException(InvalidArgumentException::class);

        EnvFile::fromString('')->set('DB_PASSWORD', "first\nsecond");
    }

    #[Test]
    public function windows_line_endings_are_normalised(): void
    {
        $rendered = EnvFile::fromString("APP_NAME=Planvio\r\nAPP_ENV=local\r\n")
            ->set('APP_ENV', 'production')
            ->render();

        $this->assertStringNotContainsString("\r", $rendered);
        $this->assertSame('production', Dotenv::parse($rendered)['APP_ENV']);
    }
}
